spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:appdb}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

sqs:
  queue:
    url: ${APPROVAL_QUEUE_URL}

app:
  base:
    url: ${APP_BASE_URL:https://example.com}

logging:
  level:
    com.example.callback: INFO
    org.springframework: WARN