AWSTemplateFormatVersion: '2010-09-09'
Description: HTTP API (IAM-restricted) with VPC Link to Internal ALB; POST /create-request

Parameters:
  VpcId:
    Type: String
    Description: VPC Id (same VPC as your ALB and ECS)

  PrivateSubnetIds:
    Type: CommaDelimitedList
    Description: Private subnet IDs for the VPC Link ENIs

  InternalALBListenerArn:
    Type: String
    Description: ARN of the Internal ALB HTTP listener (e.g., !ImportValue ApprovalInternalALBListenerArn)

  InternalALBSecurityGroupId:
    Type: String
    Description: Security Group ID attached to the Internal ALB (e.g., !ImportValue ApprovalInternalALBSecurityGroupId)

  AllowedPrincipalArn:
    Type: String
    Description: IAM principal (e.g., Step Functions execution role ARN) allowed to invoke the API
    # Example: arn:aws:iam::123456789012:role/approval-sfn-exec-role

  DummyParam:
    Type: String
    Default: "EMPTY"

Resources:

  VpcLinkSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG for API Gateway VPC Link ENIs (egress to ALB:80)
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          DestinationSecurityGroupId: !Ref InternalALBSecurityGroupId

  PrivateHttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      # Define HTTP API without OpenAPI Body/paths
      ProtocolType: "HTTP"
      CorsConfiguration: {}
      DisableExecuteApiEndpoint: false
      Name: "approval-iam-restricted-http-api"

  PrivateHttpApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref PrivateHttpApi
      StageName: "$default"
      AutoDeploy: true

  PrivateVpcLink:
    Type: AWS::ApiGatewayV2::VpcLink
    Properties:
      Name: approval-iam-vpc-link
      SubnetIds: !Ref PrivateSubnetIds
      SecurityGroupIds: [ !Ref VpcLinkSecurityGroup ]

  CreateRequestIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref PrivateHttpApi
      IntegrationType: HTTP_PROXY
      ConnectionType: VPC_LINK
      ConnectionId: !Ref PrivateVpcLink
      IntegrationMethod: POST
      IntegrationUri: !Ref InternalALBListenerArn
      PayloadFormatVersion: '1.0'
      TimeoutInMillis: 29000

  FinalizeIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref PrivateHttpApi
      IntegrationType: HTTP_PROXY
      ConnectionType: VPC_LINK
      ConnectionId: !Ref PrivateVpcLink
      IntegrationMethod: POST
      IntegrationUri: !Ref InternalALBListenerArn
      PayloadFormatVersion: '1.0'
      TimeoutInMillis: 29000

  CreateRequestRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref PrivateHttpApi
      RouteKey: "POST /create-request"
      Target: !Sub "integrations/${CreateRequestIntegration}"
      AuthorizationType: AWS_IAM

  FinalizeRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref PrivateHttpApi
      RouteKey: "POST /finalize"
      Target: !Sub "integrations/${FinalizeIntegration}"
      AuthorizationType: AWS_IAM

  AlbIngressFromVpcLink:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref InternalALBSecurityGroupId
      SourceSecurityGroupId: !Ref VpcLinkSecurityGroup
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80

Outputs:
  HttpApiId:
    Value: !Ref PrivateHttpApi
    Description: HTTP API ID
    Export:
      Name: ApprovalRestrictedApiId

  ApiEndpoint:
    Value: !Sub "${PrivateHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
    Description: Public execute-api endpoint (IAM restricted)
    Export:
      Name: ApprovalRestrictedApiEndpoint

  VpcLinkId:
    Value: !Ref PrivateVpcLink
    Description: VPC Link ID
    Export:
      Name: ApprovalCreateRequestVpcLinkId

  VpcLinkSecurityGroupId:
    Value: !Ref VpcLinkSecurityGroup
    Description: SG used by API GW VPC Link ENIs
    Export:
      Name: ApprovalCreateRequestVpcLinkSgId