AWSTemplateFormatVersion: '2010-09-09'
Description: Callback Consumer Service

Parameters:
  VpcId:
    Type: String
  PrivateSubnetIds:
    Type: CommaDelimitedList
  ECSClusterName:
    Type: String
  ECSSecurityGroupId:
    Type: String
  DbSecretArn:
    Type: String
  DbHost:
    Type: String
  DbPort:
    Type: String
  DbName:
    Type: String
  ApprovalQueueUrl:
    Type: String
  ImageUri:
    Type: String
  AppBaseUrl:
    Type: String

Resources:
  # Task Definition
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: callback-service
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !GetAtt ExecutionRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - Name: callback-service
          Image: !Ref ImageUri
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
          Environment:
            - Name: DB_HOST
              Value: !Ref DbHost
            - Name: DB_PORT
              Value: !Ref DbPort
            - Name: DB_NAME
              Value: !Ref DbName
            - Name: SQS_QUEUE_URL
              Value: !Ref ApprovalQueueUrl
            - Name: APP_BASE_URL
              Value: !Ref AppBaseUrl
          Secrets:
            - Name: DB_USERNAME
              ValueFrom: !Sub "${DbSecretArn}:username::"
            - Name: DB_PASSWORD
              ValueFrom: !Sub "${DbSecretArn}:password::"

  # ECS Service
  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: callback-service
      Cluster: !Ref ECSClusterName
      TaskDefinition: !Ref TaskDefinition
      LaunchType: FARGATE
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: !Ref PrivateSubnetIds
          SecurityGroups: [!Ref ECSSecurityGroupId]
          AssignPublicIp: DISABLED

  # Execution Role
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource: !Ref DbSecretArn

  # Task Role
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SQSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !Sub "${ApprovalQueueUrl}*"

  # CloudWatch Log Group
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/callback-service
      RetentionInDays: 7

Outputs:
  ServiceArn:
    Value: !Ref Service
    Description: ARN of the ECS Service