AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Dynamic app parts for Human Approval Workflow (Lambdas, Step Functions, API)

Parameters:
  VpcId:
    Type: String
  PrivateSubnetIds:
    Type: CommaDelimitedList
  DbSecretArn:
    Type: String
  DbHost:
    Type: String
  DbPort:
    Type: String
    Default: "5432"
  DbName:
    Type: String
    Default: "appdb"
  ApprovalQueueUrl:
    Type: String
  ApprovalQueueArn:
    Type: String
  EmailTopicArn:
    Type: String
    Default: ""
  DbSecurityGroupId:
    Type: String

Globals:
  Function:
    Runtime: python3.12
    Timeout: 15
    MemorySize: 256
    Environment:
      Variables:
        DB_SECRET_ARN: !Ref DbSecretArn
        DB_HOST: !Ref DbHost
        DB_PORT: !Ref DbPort
        DB_NAME: !Ref DbName
        SNS_TOPIC_ARN: !Ref EmailTopicArn
    VpcConfig:
      SecurityGroupIds: [!Ref LambdaSecurityGroup]
      SubnetIds: !Ref PrivateSubnetIds
    Layers:
      - !Ref Psycopg2Layer

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins: ['*']
        AllowHeaders: ['*']
        AllowMethods: ['*']

  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Lambda SG for DB access
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  DbIngressFromLambda:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref DbSecurityGroupId
      SourceSecurityGroupId: !Ref LambdaSecurityGroup
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432

  Psycopg2Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: psycopg2-layer
      ContentUri: ../src/psycopg2-layer/
      CompatibleRuntimes:
        - python3.12
    Metadata:
      BuildMethod: python3.12

  StartExecutionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: start_execution
      CodeUri: ../src/start_execution
      Handler: app.handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Environment:
        Variables:
          STATE_MACHINE_ARN: !GetAtt ApprovalStateMachine.Arn
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: states:StartExecution
              Resource: !GetAtt ApprovalStateMachine.Arn
      Events:
        StartApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /intiateworkflow
            Method: POST

  CreateRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/create_request/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Ref DbSecretArn

  CallbackConsumerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          APP_BASE_URL: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"
      CodeUri: ../src/callback_consumer/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !Ref ApprovalQueueArn
            BatchSize: 5
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Ref DbSecretArn
            - Effect: Allow
              Action: sns:Publish
              Resource: !If [HasEmailTopic, !Ref EmailTopicArn, !Ref 'AWS::NoValue']

  ResumeWorkflowFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/resume_workflow/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Events:
        ResumeApiPost:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /requests/{taskId}/decision
            Method: POST
        ResumeApiGet:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /requests/{taskId}/decision
            Method: GET
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Ref DbSecretArn
            - Effect: Allow
              Action:
                - states:SendTaskSuccess
                - states:SendTaskFailure
              Resource: "*"

  FinalizeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/finalize/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Ref DbSecretArn

  ApprovalStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: approval-workflow
      Type: STANDARD
      DefinitionUri: statemachine/approval_workflow.asl.json
      DefinitionSubstitutions:
        CreateRequestArn: !GetAtt CreateRequestFunction.Arn
        FinalizeArn: !GetAtt FinalizeFunction.Arn
        QueueUrl: !Ref ApprovalQueueUrl
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref CreateRequestFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref FinalizeFunction
        - SQSSendMessagePolicy:
            QueueName: !Select [5, !Split [":", !Ref ApprovalQueueArn]]

Conditions:
  HasEmailTopic: !Not [!Equals [!Ref EmailTopicArn, ""]]

Outputs:
  ApiEndpoint:
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"
  StateMachineArn:
    Value: !GetAtt ApprovalStateMachine.Arn
  CreateRequestFunctionName:
    Value: !Ref CreateRequestFunction
  CallbackConsumerFunctionName:
    Value: !Ref CallbackConsumerFunction
  ResumeWorkflowFunctionName:
    Value: !Ref ResumeWorkflowFunction
  FinalizeFunctionName:
    Value: !Ref FinalizeFunction
